#!/bin/sh
# build-wasm.sh — build the fx-init userland demo shell to WebAssembly.
#
# ONE module bundles the real userland CLIs — fxstore, fx-activate, fxctl,
# dhall — over the shared in-process dhall-c + datalog-dafsa + dafsa cores,
# linked from THIS repo's vendored submodules (so engine/DAFSA versions match
# fx-init's own native builds exactly). The tools' main()s are renamed per
# translation unit and dispatched by src/fx-shell-wasm.c:fxsh_run().
#
# Requires emscripten + node. On Arch:  pacman -S emscripten clang lld llvm nodejs
# Artifacts are COMMITTED under shell/wasm/ (dhall-c / datalog-dafsa / shen
# precedent: no CI wasm build). scripts/ssg.mjs copies shell/ -> dist/.
set -eu
cd "$(dirname "$0")/.."

EMCONF=$(mktemp)
trap 'rm -f "$EMCONF"' EXIT
cat > "$EMCONF" <<'EOF'
import os
NODE_JS = '/usr/bin/node'
LLVM_ROOT = '/usr/bin'
BINARYEN_ROOT = '/usr'
EMSCRIPTEN_ROOT = '/usr/lib/emscripten'
CACHE = os.path.expanduser('~/.cache/emscripten')
EOF
EMCC=/usr/lib/emscripten/emcc

BUILD=build-wasm
OUT=shell/wasm
mkdir -p "$BUILD" "$OUT"

# dhall-c core — the exact CORE list from dhall-c/scripts/build-wasm.sh
# (wasm.c and lsp.c are NOT linked; main.c is, renamed).
DHC=vendor/dhall-c/src
DHALL_SRC="$DHC/arena.c $DHC/lexer.c $DHC/parser.c $DHC/ast.c $DHC/normalize.c $DHC/typecheck.c $DHC/builtins.c $DHC/serialize.c $DHC/import.c $DHC/bignum.c $DHC/sha256.c $DHC/http.c"

# datalog-dafsa engine core — VERBATIM the proven-wasm CORE list from
# datalog-dafsa/scripts/build-wasm.sh (dl.c's snapshot/WAL/dafsa_view POSIX
# surface — mmap MAP_PRIVATE, fcntl, opendir, fsync, rename, mkdir — is all
# MEMFS-backed emscripten libc; it links with no stubbing). dl_cli.c (which
# pulls index.c + vector.c) is deliberately NOT linked.
DL=vendor/datalog-dafsa/src
DAF=vendor/dafsa
DL_SRC="$DL/intern.c $DL/termstore.c $DL/relation.c $DL/vrelation.c $DL/tupleset.c $DL/parser.c $DL/compiler.c $DL/vm.c $DL/snapshot.c $DL/regexwalk.c $DL/permindex.c $DL/util.c $DL/dl.c $DL/txnwal.c $DL/iter.c $DL/magic.c $DL/topdown.c $DL/analyze.c $DL/schema.c $DL/typecheck.c $DAF/dafsa.c $DAF/dafsa_state.c $DAF/dafsa_core.c $DAF/dafsa_persist.c $DAF/dafsa_view.c $DAF/dafsa_crc32.c $DAF/dafsa_wal.c $DAF/dafsa_build.c $DAF/dafsa_rank.c $DAF/dafsa_view_rank.c"

FXS=vendor/fxstore
CFLAGS="-O2 -D_XOPEN_SOURCE=700 -include limits.h -I src -I $FXS -I $DHC -I $DL -I $DAF"

# 1. per-TU renamed mains (each compiled alone so -Dmain applies only there)
EM_CONFIG="$EMCONF" $EMCC $CFLAGS -Dmain=fxstore_main     -c $FXS/main.c         -o $BUILD/fxstore_main.o
EM_CONFIG="$EMCONF" $EMCC $CFLAGS -Dmain=fx_activate_main -c src/fx-activate.c   -o $BUILD/fx_activate_main.o
EM_CONFIG="$EMCONF" $EMCC $CFLAGS -Dmain=fxctl_main       -c src/fxctl.c         -o $BUILD/fxctl_main.o
EM_CONFIG="$EMCONF" $EMCC $CFLAGS -Dmain=dhall_main       -c $DHC/main.c         -o $BUILD/dhall_main.o

# 2. one link: dispatcher + renamed mains + fxstore units + fx-activate
#    support (config.c) + dhall core + datalog core + dafsa vendor.
EM_CONFIG="$EMCONF" $EMCC $CFLAGS \
  -s MODULARIZE=1 -s EXPORT_NAME=createFxShell \
  -s EXPORTED_FUNCTIONS=_fxsh_run,_malloc,_free \
  -s EXPORTED_RUNTIME_METHODS=ccall,cwrap,stringToUTF8,UTF8ToString,FS,HEAPU8 \
  -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=67108864 -s TOTAL_STACK=8388608 \
  -s FORCE_FILESYSTEM=1 -s INVOKE_RUN=0 -s EXIT_RUNTIME=0 \
  -o "$OUT/fx-shell.cjs" \
  src/fx-shell-wasm.c \
  $BUILD/fxstore_main.o $BUILD/fx_activate_main.o $BUILD/fxctl_main.o $BUILD/dhall_main.o \
  $FXS/packageset.c $FXS/derivation.c $FXS/closure.c $FXS/store.c $FXS/build.c \
  src/config.c \
  $DHALL_SRC $DL_SRC

# 3. emit the demo dhall sources as a JS module (single source of truth:
#    demo/*.dhall in the repo, inlined for the browser boot sequence).
#    U1 has no demo/*.dhall yet — skip until they exist (artifact-3).
if [ -f demo/package-set.dhall ] && [ -f demo/config.dhall ]; then
node -e '
const fs = require("fs");
const esc = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
const ps = fs.readFileSync("demo/package-set.dhall", "utf8");
const cf = fs.readFileSync("demo/config.dhall", "utf8");
fs.writeFileSync("shell/wasm/demo-files.js",
  "// generated by scripts/build-wasm.sh from demo/*.dhall — do not edit\n" +
  "export const PACKAGE_SET = `" + esc(ps) + "`;\n" +
  "export const CONFIG = `" + esc(cf) + "`;\n");
'
fi

# 4. smoke test (node; also the CI-able regression gate)
node tests/fxshell-smoke.js
ls -la "$OUT/fx-shell.cjs" "$OUT/fx-shell.wasm"
